--- pyproject.toml.orig	2021-02-26 23:46:12 UTC
+++ pyproject.toml
@@ -3,5 +3,5 @@ build-backend = "setuptools.build_meta"
 requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]
 
 [tool.setuptools_scm]
-fallback_version = "unknown"
+fallback_version = "0.4.3"
 local_scheme = "no-local-version"
